remote_theme: rnand/just-the-docs
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jemoji
# Aux links for the upper right navigation
aux_links:
    "സി എം ബി സിമുലേറ്റര്‍":
      - "https://rnand.github.io/planckapps/Simulator/"
